Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
    Enabled: false

Style/ClassVars:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Metrics/MethodLength:
  Max: 30

Metrics/ClassLength:
  Enabled: false
